### ISSUE TITLE
Open source mod.

### ISSUE THREAD

**Issue by ghost** [PiMoNFeeD/csso-tracker#15]
Relevant discussion in Discord: [click.](https://discord.com/channels/731204789073084466/747409280856227840/781285006307491892)
 
The main problem is that sources are **really** bloated (47 GB!!!).

**Comment by PiMoNFeeD** [comment]
done

**Comment by maksw2** [comment]
but why not

**Comment by PiMoNFeeD** [comment]
> but why not

because it was, and it ended up a really fucking bad idea

**Comment by maksw2** [comment]
I saw a few forks out there, I love the work that you did on the engine! I was just wondering if my team could use it.

**Comment by PiMoNFeeD** [comment]
> I saw a few forks out there, I love the work that you did on the engine! I was just wondering if my team could use it.

there's nothing special about it, the code is quite bad in fact, and all the forks are several years outdated from the latest build which in itself is already over a year old
