### ISSUE TITLE
0.11 Bug report

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csso-tracker#23]
### BUGS 0.11
    **Buy menu**
    -When you are outside of buy zone you can buy kevlar and helm with BIND or typing in console (competitive)
    "buy assaultsuit | buy kevlar"

    **Bot bug**
    -When you pick a bot and you lose or win the round the bot don't win money 
    (if the round end and you controlling bot) and this cause the bot have a permanent eco

    **Grenade duplication glitch**
    -If you trow a grenade and drop instantly the grenade is trowed and dropped
    
    **Fake Reload Bug**
    -you can't do a fake reload, the game forces wait a complete reload time

    **HUD**
    -The hud don't update in spectator mode (weapon changes)
    -The hud in hide mode cause epilepsia in certain resolutions
    -The text description in some weapons is broken in high resolutions (1366x768)

    **Kick system**
    -If you try kick a player and he left the game without the system kicks and rejoin again the host crash

    **Overtime System**
    -In some cases in first overtime round, the round wining team don't receive 10k and still weapons
    
    **Zoom bug**
    -if you zoom with every sniper and press reload the zoom resets but the scope still
    

### Suggestions
	-Rework the scoreboard in 4:3 because the complete map is hidden
	-Add the flash assist
	-Remove the left handed c4 ._.

 
### Code suggestions
	-In c_particle_smokegrenade.cpp
	float flCoreDistance = fadeEnd * 0.6; //deep smoke

	-Remove in weapon_c4.cpp
	//Emitsound(Filter, entindex(), "c4.click") //remove the clicking sound when the bomb is planting (don't remove the beep sound)

-Pls don't leave the csso development
- 					an CSSO FAN.

**Comment by PiMoNFeeD** [comment]
ok first of all: why would i leave csso development wtf???
second, half of these is already fixed, im surprised your really loving fanbase didnt tell you that because its literally written in my discord server
third, i see absolutely no reason to put the code suggestions that you mentioned
fourth, its OBVIOUS that im going to completely rework the scoreboard because its literally a CSS scoreboard whats the point of your suggestion??
fifth, the "fake reload" thing is literally how it is SUPPOSED TO BE are you good?

and wtf does "weapon description" even mean? i dont have any weapon descriptions, also 1366x768 is nowhere close to being a big resolution

**Comment by NOMFPS** [comment]
1. I read you are now working in another source game
2. IDK because you publish your code updates only in discord, 2.1 the people like amar, hampta its so toxic and you know
3. It's only a suggestions 
4. Nice
5. XD, its only when the timer is 0 or have mp_ignore_round_win_conditions "1" (try it with negev XD)
6. Like https://media.discordapp.net/attachments/791842859811995688/909939138084606002/unknown.png
7. I updated the comment again

**Comment by PiMoNFeeD** [comment]
> people like amar, hampta its so toxic and you know

are you retarded?
![image](https://user-images.githubusercontent.com/36343425/148700791-dedcc3a5-2a1e-4ced-a0b0-b280c84c0645.png)

the thing that you call "weapon descriptions" is not broken thank valve for their retarded font renderer

**Comment by NOMFPS** [comment]
1. I'm not on your server, but those two guys have done worse things on your server, (search in sv history when i put the nickname)
2. XD

**Comment by PiMoNFeeD** [comment]
ok you are actually mentally
