### ISSUE TITLE
The footsteps are bugged

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csso-tracker#24]
### The footsteps have a low volume.
In CSS the volume value is 127.
cap: https://media.discordapp.net/attachments/791842859811995688/936044639817977937/unknown.png
In CSSO the value of volume 63 (half of CSS).
cap: https://media.discordapp.net/attachments/791842859811995688/936041814044074044/unknown.png
In CSGO the volume value (250).
The other player's footsteps have low volume, while landing sounds are loudness (250).
cap: https://media.discordapp.net/attachments/791842859811995688/936041991286947880/unknown.png
cvars: snd_show 1

### The Bot's aim target are in the foots
the bots only aim at the knee, never aim at the chest or head
cap:  https://media.discordapp.net/attachments/791842859811995688/936372040208908388/unknown.png

**Comment by PiMoNFeeD** [comment]
have you even heard how footsteps sound? if i tune them up you will be literally DEAF by your own footsteps dude, i dont care about raw numbers, listen to the actual sounds instead

and about bots: blame valve for that and you KNOW it

**Comment by NOMFPS** [comment]
> have you even heard how footsteps sound? if i tune them up you will be literally DEAF by your own footsteps dude, i dont care about raw numbers, listen to the actual sounds instead.

put CSGO on the same spot with another player and hear the footsteps, 
now do the same with CSSO with other player and hear,
if you don't differentiate, i guess you're deaf
the local player footsteps are normal, the problem are the other footsteps player

**Comment by PiMoNFeeD** [comment]
> > have you even heard how footsteps sound? if i tune them up you will be literally DEAF by your own footsteps dude, i dont care about raw numbers, listen to the actual sounds instead.
> 
> put CSGO on the same spot with another player and hear the footsteps, now do the same with CSSO with other player and hear, if you don't differentiate, i guess you're deaf the local player footsteps are normal, the problem are the other footsteps player

do you even read what i tell you? local player footsteps are normal because i had to lower the volume by 70% because there is no difference between local and remote footsteps omg, if i put it to 100% then you are going to be frecking deaf by your local footsteps
