### ISSUE TITLE
New Particle System Crash and Suggestion

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csso-tracker#25]
### BUG:
**cl_new_impact_effects 1** have missing particles and causes crash on classic maps
if you already fixed ignore it

### Suggestion:
-Add the CSGO sound system
or fix the current CSSO sound system because is broken

-Add support to hammer++ CSGO if you can
or fix crashes when map is loading in legacy hammer i can't make maps ._ .

**Comment by PiMoNFeeD** [comment]
you are not supposed to use cl_new_impact_effects at this point

adding csgo sound system is not possible at this stage
wtf does "csso sound system is broken" even mean? i never even edited the soundsystem in csso :facepalm: 

how am i supposed to add hammer++ support?? its not csso that should have hammer++ support, its hammer++ that should have csso support
i dont have any crashes so i cant fix something that doesnt happen to me, why do you even use a legacy hammer, csso has its own hammer

**Comment by NOMFPS** [comment]
0.12 support? :thinking: 

when you add the land sound the sound system is broken you can try hear installing csso 0.1 0.2 0.3 0.4 0.5 or 0.61, and only hear the difference between other player footsteps and player sounds 
i know you don't touch the sound system but i mean is broken itself :thinking: 

CSSO legacy hammer crash when i try to port some map for csgo :crying_cat_face:
