### ISSUE TITLE
Player's back have deaf zone

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csso-tracker#26]
i find when i playing nuke, if you have door at back and other player opens or runs you can't hear 
in specific range, i don't know if is intended or you already solved

video:
https://cdn.discordapp.com/attachments/791842859811995688/965687776043479050/Nomuser_2022-04-18_09-51-38-612-1-1.mp4
Demo & map:
https://cdn.discordapp.com/attachments/791842859811995688/965688283180961902/demo-and-map.rar

**Comment by PiMoNFeeD** [comment]
so what am i supposed to do with it? ask valve to fix their broken sound system? can you stop abusing this 20 yrs old piece of code that nobody's gonna touch today?

**Comment by PiMoNFeeD** [comment]
also, its likely that you have incorrect speaker setup in audio settings
