### ISSUE TITLE
Do #15 again?

### ISSUE THREAD

**Issue by thenomuser** [PiMoNFeeD/csso-tracker#28]
Pls do #15 
Or pls do a build of engine.dll without steam verificación because My Friends can't play on My dedícated server
No one wins without #15 
Don't do for me, do for them
Reléase the 1.0 code in a zip or pls remove steam validation in a build
I won't do custom again because i now not play csso every day. i'm out.
Tell me reasons

**Comment by PiMoNFeeD** [comment]
you are actually an idiot
